### ISSUE TITLE
Hardcoded Carafe.fmp12

### ISSUE THREAD

**Issue by toddgeist** [carafe-fm/carafe-js#1]
I have this working now pretty much the way I like for building our widgets.  So good job :-)

One question though.  Could we add filename and script to run on push to the carafe settings?  Right now it is hardcoded to Carafe.fmp12

**Comment by jeremiahsmall** [comment]
Definitely. That is hardcoded in the bin file: https://github.com/carafe-fm/carafe-bundler/blob/927d6334c7521d9f585437849b126603bbba4f00/bin/compile-carafe-bundle.js#L70

**Comment by jeremiahsmall** [comment]
Let's move this discussion over to the bundler project. Do you want to take a swing at a PR for this change?
